DROP TABLE IF EXISTS memory_fact_trigger_embedding;
DROP TABLE IF EXISTS memory_fact_trigger;
DROP TABLE IF EXISTS memory_schema_migration;
DROP TABLE IF EXISTS memory_fact_embedding;
DROP TABLE IF EXISTS memory_fact_circle;
DROP TABLE IF EXISTS memory_job;
DROP TABLE IF EXISTS memory_profile;
DROP TABLE IF EXISTS memory_fact;
DROP TABLE IF EXISTS memory_episode;
