package agentruntime

import (
	"strings"

	"github.com/yeomyeonggeori/bluecollar/agentcontract"
)

func hostInstructionForRequest(request agentcontract.AgentTurnRequest) string {
	instruction := "\n\nApprovals and user input: Ask the user only when their choice or free-form input is required. Never call ask.confirm. Invoke capability and file operations directly; the runtime evaluates structured approval policy and pauses before execution when approval is required. For terminal_run, set approvalRequired=true with an approvalReason only when your judgment is that the exact command requires the user's confirmation; otherwise omit it or set it false. Deleting a workspace file the user named follows the runtime approval path: find the file yourself (ls ~/documents) and call file_delete directly. Use ask_input for free-form missing information and for explicit choices: pass choices=[] for open input, or a non-empty choices array when the user should pick an option or type a different answer. Reading or listing workspace data such as calendar events, tasks, or files never needs approval. If no user input is pending, call finish or proceed directly."
	instruction += " For ask_input, put the exact question shown to the user in the action message field, written in the same language as the original user request — there is no separate userFacingMessage field."
	instruction += " When a continue call invokes an operation that needs approval before it runs — sending a message or email to someone, or adding, updating, or deleting a calendar event — put a one-line confirmation of exactly what you will do (recipient and content, or the calendar change) in the action message field, in the user's language. Write it as a natural user-facing question such as \"테스트에게 다음 내용을 보낼까요?\" instead of naming internal tools or operations. The runtime uses that message as the approval-question draft, so it must not be empty even on a simple task; this overrides the rule to keep continue.message empty."
	if request.IsApprovalContinuation {
		instruction += " The user just approved the pending sensitive action in their latest message. The runtime has already performed that approved action before this model step. Review the resulting observation and finish; do not call the approved tool again and do not call ask_confirm again for the same action."
	}
	instruction += "\n\nRecipients: Send capabilities resolve recipient names internally, including partial names, usernames, and emails — pass the name the user gave as personHint without searching memory or the web for contact details, and never ask the user for account IDs or handles. Resolving the recipient is the send capability's own job: do not search for, disambiguate, or invent the recipient yourself before invoking it. The only valid source of recipient candidates is the capability's own recipient_ambiguous result, so do not call ask_input to pick a recipient unless that result actually returned recipient_ambiguous, and then offer exactly the candidates it returned as choices. Do not invent candidates or guess who the user meant before the capability reports back. On recipient_ambiguous pick the person with ask_input choices from the returned candidates; on recipient_not_found tell the user that name is not registered and ask only for the correct name."
	instruction += "\n\nPrivacy boundary applies to direct messages and channels, NOT to work tasks. Direct messages and channels are private: only read or post the requester's own DMs and the channels they belong to. Never read or post another person's private DMs, and never read or post in a channel the requester is not a member of; if asked, decline up front (only that person can see their own DMs, and only channel members can see a channel) and do not attempt the capability call. This applies to every requester including admins — admin status does not grant access to other people's DMs or channels through you, and the runtime also denies it, so attempting it only wastes a step. Work tasks are shared, not private: you may look up anyone's tasks. task_list defaults to the requester's tasks. Set targetPersonHint for one specific person, or scope to all only when the user explicitly asks for workspace-wide tasks. Never tell the user you can only see their own tasks."
	return strings.TrimSpace(instruction)
}
